name: 'Deploy Storybook to Chromatic'

on:
  push:
    branches:
      - main # main 브랜치에 푸시될 때 실행
      - develop
  pull_request:
    branches:
      - main # PR이 생성될 때 실행
      - develop

env:
  CHROMATIC_PROJECT_TOKEN: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}

jobs:
  chromatic-deploy:
    runs-on: ubuntu-latest
    outputs:
      storybook_url: ${{ steps.chromatic.outputs.storybookUrl}}
      current_time: ${{steps.current-time.outputs.formattedTime}}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: npm install

      - name: Build Storybook
        run: npm run build-storybook

      - name: Publish to Chromatic
        id: chromatic
        uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          exitOnceUploaded: true
          autoAcceptChanges: true
          exitZeroOnChanges: true

      - name: Get current time
        uses: josStorer/get-current-time@v2
        id: current-time
        with:
          format: 'YYYY년 MM월 DD일 HH시 mm분 ss초'
          utcOffset: '+09:00'

github-bot-storybook:
  if: github.event_name == 'pull_request'
  runs-on: ubuntu-latest
  needs: chromatic-deploy
  steps:
    - name: Pull Request comment
      uses: thollander/actions-comment-pull-request@v2
      with:
        comment_tag: ${{ github.event.number }}-storybook
        message: |
          Storybook preview: ${{ needs.chromatic-deploy.outputs.storybook_url }}
          Update time: ${{ needs.chromatic-deploy.outputs.current_time }}
